apiVersion: v2
name: objects
description: A Helm chart for Objects API

type: application
version: 0.1.1
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: ~10.10.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
  - name: redis
    version: ~13.0.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
