tags:
  postgresql: true
  redis: true

replicaCount: 1

image:
  repository: maykinmedia/objects-api
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

existingSecret: null

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

settings:
  secretKey: NOT-SO-SECRET
  allowedHosts: "objects.gemeente.nl"
  admins: ""
  siteId: ""
  debug: "False"
  isHttps: "True"
  subPath: ""
  notificationsDisabled: "False"
  twoFactorForceOtpAdmin: "True"
  twoFactorPatchAdmin: "True"

  database:
    host: objects-postgresql
    port: 5432
    username: postgres
    password: objects
    name: postgres
  
  cache:
    default: open-zaak-redis-master:6379/0
    axes: open-zaak-redis-master:6379/0

  sentry:
    dsn: ""

#########################
## PostgreSQL subchart ##
#########################
postgresql:
  postgresqlPassword: objects
  postgresqlPostgresPassword: objects
  image.tag: 12.8.0


##################
# Redis subchart #
##################

redis:
  usePassword: false

  cluster:
    enabled: false

  persistence:
    existingClaim: null

  master:
    persistence:
      enabled: false
      size: 1Gi